apiVersion: v1
kind: Service
metadata:
  name: ssh-access
spec:
  ports:
  - port: 22
    targetPort: 22
  selector:
    app: rhel9-nfs-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-access
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhel9-nfs-server
  template:
    metadata:
      labels:
        app: rhel9-nfs-server
    spec:
      containers:
      - name: ssh
        image: alpine:latest
        command: ["/bin/sh", "-c", "apk add --no-cache openssh; /usr/sbin/sshd -D"]
        ports:
        - containerPort: 22
